name: 'Coverage Steps'
description: 'Build project, run tests, and generate coverage report for sol-ui'
runs:
  using: 'composite'
  steps:
    - name: Check platform compatibility
      run: |
        echo "This project requires macOS to build due to Metal/CoreGraphics dependencies"
        if [[ "${{ runner.os }}" != "macOS" ]]; then
          echo "::warning::Running on ${{ runner.os }} - will create mock coverage report"
        fi
      shell: bash

    - name: Install Rust (if on macOS)
      if: runner.os == 'macOS'
      uses: dtolnay/rust-action@nightly
      with:
        components: llvm-tools-preview

    - name: Install coverage tools (if on macOS)
      if: runner.os == 'macOS'
      uses: taiki-e/install-action@cargo-llvm-cov

    - name: Build project (if on macOS)
      if: runner.os == 'macOS'
      run: cargo build --release
      shell: bash

    - name: Run tests with coverage (if on macOS)
      if: runner.os == 'macOS'
      run: |
        cargo llvm-cov --all-features --cobertura --output-path coverage/cobertura.xml
        cargo llvm-cov report --html --output-dir coverage/html
      shell: bash

    - name: Create mock coverage report (if not on macOS)
      if: runner.os != 'macOS'
      run: |
        mkdir -p coverage
        cat > coverage/index.html << 'EOF'
        <html>
        <head><title>Coverage Report - macOS Required</title></head>
        <body>
        <h1>Sol UI Test Coverage</h1>
        <p><strong>Note:</strong> This project requires macOS to build and generate actual coverage reports.</p>
        <p>To generate real coverage, run on macOS:</p>
        <pre>
        cargo install cargo-llvm-cov
        cargo llvm-cov --all-features --html --output-dir coverage/
        </pre>
        </body>
        </html>
        EOF

        cat > coverage/cobertura.xml << 'EOF'
        <?xml version="1.0" encoding="UTF-8"?>
        <coverage>
          <sources><source>.</source></sources>
          <packages>
            <package name="sol-ui">
              <classes>
                <class name="mock" filename="src/lib.rs">
                  <!-- Mock coverage - actual coverage requires macOS -->
                </class>
              </classes>
            </package>
          </packages>
        </coverage>
        EOF
      shell: bash

    - name: Upload coverage report as artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: coverage/
        retention-days: 30